# Generated by Django 6.0.2 on 2026-02-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Text shown on the back of the flip card', max_length=255)),
                ('image', models.ImageField(upload_to='collections/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collection Card',
                'verbose_name_plural': 'Collection Cards',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='featured/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Collection',
                'verbose_name_plural': 'Featured Collections',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HOUSE OF AMBAVA', max_length=100)),
                ('subtitle', models.CharField(default='Exquisite Elegance Redefined', max_length=200)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParallaxSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Experience Elegance', max_length=100)),
                ('subtitle', models.CharField(default='Every piece tells a story of craftsmanship and tradition', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='parallax/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parallax Section',
                'verbose_name_plural': 'Parallax Section',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='showcase/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Showcase Product',
                'verbose_name_plural': 'Showcase Products',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
