# Generated by Django 6.0.2 on 2026-02-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcollection',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-99). Leave 0 for no discount.'),
        ),
        migrations.AddField(
            model_name='featuredcollection',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price after discount. Auto-calculated if left blank.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-99). Leave 0 for no discount.'),
        ),
        migrations.AddField(
            model_name='showcaseproduct',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price after discount. Auto-calculated if left blank.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcollection',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original MRP', max_digits=10),
        ),
        migrations.AlterField(
            model_name='showcaseproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original MRP', max_digits=10),
        ),
    ]
