# Generated by Django 6.0.2 on 2026-02-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_featuredcollection_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload a background video — MP4 recommended (used when media type is Video)', null=True, upload_to='hero/videos/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose whether the background is an image or video', max_length=5),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload a background image (used when media type is Image)', null=True, upload_to='hero/'),
        ),
    ]
