# Generated by Django 6.0.2 on 2026-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_herosection_background_video_herosection_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseproduct',
            name='category',
            field=models.CharField(choices=[('bridal', 'Bridal'), ('designer', 'Designer'), ('festival', 'Festival'), ('party', 'Party Wear'), ('casual', 'Casual')], default='bridal', max_length=20),
        ),
    ]
