# Generated by Django 6.0.2 on 2026-02-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_showcaseproduct_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional product image', upload_to='showcase/gallery/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Image description (e.g. Back View, Detail)', max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = appears first')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.showcaseproduct')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order'],
            },
        ),
    ]
