# Generated by Django 6.0.2 on 2026-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+91 (123) 456-7890', max_length=30)),
                ('email', models.EmailField(default='info@houseofambava.com', max_length=254)),
                ('address', models.CharField(default='New Delhi, India', max_length=200)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('pinterest_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp number with country code e.g. 919876543210', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Shop', max_length=100)),
                ('subtitle', models.CharField(default='Discover handcrafted lehengas that tell a story of elegance and tradition', max_length=255)),
                ('badge_text', models.CharField(default='CURATED COLLECTION', help_text='Small badge text above the title', max_length=50)),
                ('media_type', models.CharField(choices=[('pattern', 'Default Pattern'), ('image', 'Image'), ('video', 'Video')], default='pattern', max_length=10)),
                ('background_image', models.ImageField(blank=True, help_text='Upload a banner image (used when media type is Image)', null=True, upload_to='shop_banner/')),
                ('background_video', models.FileField(blank=True, help_text='Upload a banner video — MP4 recommended', null=True, upload_to='shop_banner/videos/')),
                ('overlay_opacity', models.PositiveIntegerField(default=60, help_text='Dark overlay opacity 0–100 (higher = darker)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Banner',
                'verbose_name_plural': 'Shop Banner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 10K+, 500+, 100%', max_length=30)),
                ('label', models.CharField(help_text='e.g. Happy Customers, Designs', max_length=60)),
                ('icon', models.CharField(blank=True, default='', help_text='Font Awesome class e.g. fas fa-users (optional)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = appears first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat Item',
                'verbose_name_plural': 'Stat Items',
                'ordering': ['display_order'],
            },
        ),
    ]
