# Generated by Django 6.0.2 on 2026-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactinfo_shopbanner_statitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Story', max_length=200)),
                ('subheading', models.CharField(blank=True, default='The Journey Behind House of Ambava', max_length=300)),
                ('main_image', models.ImageField(help_text='Main portrait/image displayed on the left side of the page', upload_to='about/')),
                ('secondary_image', models.ImageField(blank=True, help_text='Optional second image for visual depth', null=True, upload_to='about/')),
                ('founder_name', models.CharField(default='Ambava', max_length=100)),
                ('founder_title', models.CharField(default='Founder & Creative Director', max_length=200)),
                ('story_text', models.TextField(help_text='The main story text about the founder and the brand')),
                ('quote_text', models.CharField(blank=True, default='', help_text='An inspirational quote from the founder', max_length=500)),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=200)),
                ('mission_text', models.TextField(blank=True, default='', help_text='Text about the brand mission and values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
                'ordering': ['-created_at'],
            },
        ),
    ]
