# Generated by Django 6.0.2 on 2026-02-26 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(help_text='Enter the pincode (e.g., 110001)', max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this product is available for delivery in this pincode')),
                ('delivery_days', models.PositiveIntegerField(default=5, help_text='Expected delivery days for this pincode')),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, help_text='Extra shipping charge for this pincode (if any)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincode_availability', to='store.showcaseproduct')),
            ],
            options={
                'verbose_name': 'Pincode Availability',
                'verbose_name_plural': 'Pincode Availabilities',
                'ordering': ['product', 'pincode'],
                'indexes': [models.Index(fields=['product', 'is_available'], name='store_pinco_product_935daf_idx'), models.Index(fields=['pincode'], name='store_pinco_pincode_0d4a3a_idx')],
                'unique_together': {('product', 'pincode')},
            },
        ),
    ]
