# Generated by Django 6.0.2 on 2026-02-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_userprofile_facebook_id_userprofile_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay (Online)')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', help_text='Razorpay order ID (order_xxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', help_text='Razorpay payment ID (pay_xxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', help_text='Razorpay payment signature', max_length=255),
        ),
    ]
